from app.models import db, RewardPoint, Card, Category, environment, SCHEMA
from sqlalchemy import inspect
from sqlalchemy.sql import text


def seed_reward_points():
    """
    Seeds reward points into the database, associating them with cards and categories.
    """
    try:
        # Check if the `reward_points` table exists using the inspector
        inspector = inspect(db.engine)
        table_exists = inspector.has_table("reward_points", schema=SCHEMA if environment == "production" else None)

        if not table_exists:
            print(f"The reward_points table does not exist in the schema {SCHEMA}. Skipping seeding.")
            return

        # Reward points data
        reward_points_data = [
          {	"card_id":	1	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All eligible purchases (up to $50,000/year)	"	},
{	"card_id":	1	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All eligible purchases (after $50,000/year)	"	},
{	"card_id":	2	,	"category_id":	26	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Everyday business purchases (up to $50,000/year)	"	},
{	"card_id":	2	,	"category_id":	26	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Everyday business purchases (after $50,000/year)	"	},
{	"card_id":	3	,	"category_id":	9	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. supermarkets (up to $6,000/year)	"	},
{	"card_id":	3	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. gas stations	"	},
{	"card_id":	3	,	"category_id":	30	,	"bonus_point":	2	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	select department stores	"	},
{	"card_id":	3	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	4	,	"category_id":	9	,	"bonus_point":	6	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. supermarkets (up to $6,000/year)	"	},
{	"card_id":	4	,	"category_id":	18	,	"bonus_point":	6	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Select U.S. streaming subscriptions	"	},
{	"card_id":	4	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. gas stations	"	},
{	"card_id":	4	,	"category_id":	11	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	transit	"	},
{	"card_id":	4	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	5	,	"category_id":	9	,	"bonus_point":	6	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. supermarkets (up to $6,000/year)	"	},
{	"card_id":	5	,	"category_id":	18	,	"bonus_point":	6	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Select U.S. streaming subscriptions	"	},
{	"card_id":	5	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	U.S. gas stations	"	},
{	"card_id":	5	,	"category_id":	11	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	transit	"	},
{	"card_id":	5	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	6	,	"category_id":	32	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Top 2 spending categories	"	},
{	"card_id":	6	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	7	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Eligible travel purchases	"	},
{	"card_id":	7	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	8	,	"category_id":	5	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights	"	},
{	"card_id":	8	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	prepaid hotels	"	},
{	"card_id":	8	,	"category_id":	26	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Key business categories & purchases > $5,000	"	},
{	"card_id":	8	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	9	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All purchases	"	},
{	"card_id":	10	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Restaurants worldwide	"	},
{	"card_id":	10	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	10	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	11	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	11	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	restaurants	"	},
{	"card_id":	11	,	"category_id":	9	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	U.S. supermarkets	"	},
{	"card_id":	11	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	12	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	12	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	restaurants	"	},
{	"card_id":	12	,	"category_id":	24	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	U.S. shipping purchases	"	},
{	"card_id":	12	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	13	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	13	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	hotels	"	},
{	"card_id":	13	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	13	,	"category_id":	9	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	U.S. supermarkets	"	},
{	"card_id":	13	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	14	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	14	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	hotels	"	},
{	"card_id":	14	,	"category_id":	34	,	"bonus_point":	1.5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Single eligible purchases > $5,000	"	},
{	"card_id":	14	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	15	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	15	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	16	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Delta purchases	"	},
{	"card_id":	16	,	"category_id":	34	,	"bonus_point":	1.5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Single eligible purchases > $5,000	"	},
{	"card_id":	16	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	17	,	"category_id":	9	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. supermarkets (up to $6,000/year)	"	},
{	"card_id":	17	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	18	,	"category_id":	9	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. supermarkets (up to $6,000/year)	"	},
{	"card_id":	18	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. gas stations	"	},
{	"card_id":	18	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	19	,	"category_id":	2	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	19	,	"category_id":	9	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. supermarkets (up to $25,000/year)	"	},
{	"card_id":	19	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights booked directly with airlines	"	},
{	"card_id":	19	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	20	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	20	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	restaurants	"	},
{	"card_id":	20	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	21	,	"category_id":	6	,	"bonus_point":	7	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hilton purchases	"	},
{	"card_id":	21	,	"category_id":	2	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	21	,	"category_id":	9	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	supermarkets	"	},
{	"card_id":	21	,	"category_id":	12	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	21	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	22	,	"category_id":	6	,	"bonus_point":	14	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hilton purchases	"	},
{	"card_id":	22	,	"category_id":	5	,	"bonus_point":	7	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights	"	},
{	"card_id":	22	,	"category_id":	7	,	"bonus_point":	7	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals	"	},
{	"card_id":	22	,	"category_id":	2	,	"bonus_point":	7	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	22	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	23	,	"category_id":	6	,	"bonus_point":	12	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hilton purchases	"	},
{	"card_id":	23	,	"category_id":	2	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	23	,	"category_id":	9	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	supermarkets	"	},
{	"card_id":	23	,	"category_id":	12	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	23	,	"category_id":	21	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	wireless	"	},
{	"card_id":	23	,	"category_id":	24	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	shipping	"	},
{	"card_id":	23	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	24	,	"category_id":	6	,	"bonus_point":	12	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hilton purchases	"	},
{	"card_id":	24	,	"category_id":	2	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	24	,	"category_id":	9	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	supermarkets	"	},
{	"card_id":	24	,	"category_id":	12	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	24	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	25	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	25	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	25	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	flights booked directly with airlines	"	},
{	"card_id":	25	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	26	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	26	,	"category_id":	2	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	26	,	"category_id":	12	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	26	,	"category_id":	24	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	shipping	"	},
{	"card_id":	26	,	"category_id":	21	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	wireless services	"	},
{	"card_id":	26	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	27	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights booked directly with airlines or prepaid hotels	"	},
{	"card_id":	27	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	28	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights booked directly with airlines or prepaid hotels	"	},
{	"card_id":	28	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	29	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Flights booked directly with airlines or prepaid hotels	"	},
{	"card_id":	29	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	30	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	30	,	"category_id":	2	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	30	,	"category_id":	8	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	groceries (up to $15,000/year)	"	},
{	"card_id":	30	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	31	,	"category_id":	30	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Lowe’s purchases	"	},
{	"card_id":	31	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	31	,	"category_id":	23	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	office supply stores	"	},
{	"card_id":	31	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	32	,	"category_id":	37	,	"bonus_point":	1.25	,	"multiplier_type":	"	Points	"	,	"notes":	"	All purchases	"	},
{	"card_id":	33	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Air France	"	},
{	"card_id":	33	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	KLM purchases	"	},
{	"card_id":	33	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	34	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Alaska Airlines purchases	"	},
{	"card_id":	34	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	35	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Alaska Airlines purchases	"	},
{	"card_id":	35	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	36	,	"category_id":	32	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Chosen category (e.g.	"	},
{	"card_id":	36	,	"category_id":	11	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	gas	"	},
{	"card_id":	36	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	dining	"	},
{	"card_id":	36	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	travel)	"	},
{	"card_id":	36	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	36	,	"category_id":	25	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	wholesale clubs	"	},
{	"card_id":	36	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	37	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	37	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	37	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	38	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	38	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	38	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	39	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	All purchases	"	},
{	"card_id":	40	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All purchases	"	},
{	"card_id":	41	,	"category_id":	32	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Chosen category (e.g.	"	},
{	"card_id":	41	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	gas stations	"	},
{	"card_id":	41	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	travel)	"	},
{	"card_id":	41	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Dining	"	},
{	"card_id":	41	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	42	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All purchases	"	},
{	"card_id":	43	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	All purchases	"	},
{	"card_id":	45	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Spirit Airlines purchases	"	},
{	"card_id":	45	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	45	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	groceries	"	},
{	"card_id":	45	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other purchases	"	},
{	"card_id":	46	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines purchases	"	},
{	"card_id":	46	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	47	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines purchases	"	},
{	"card_id":	47	,	"category_id":	23	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Office supply	"	},
{	"card_id":	47	,	"category_id":	19	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	telecom	"	},
{	"card_id":	47	,	"category_id":	7	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	car rentals	"	},
{	"card_id":	47	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	48	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Gas	"	},
{	"card_id":	48	,	"category_id":	28	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	drugstore purchases	"	},
{	"card_id":	48	,	"category_id":	29	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Medical expenses	"	},
{	"card_id":	48	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	49	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Airfare	"	},
{	"card_id":	49	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	hotels	"	},
{	"card_id":	49	,	"category_id":	7	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	car rentals	"	},
{	"card_id":	49	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Restaurant purchases	"	},
{	"card_id":	49	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	50	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Carnival purchases	"	},
{	"card_id":	50	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	51	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Emirates purchases	"	},
{	"card_id":	51	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hotel	"	},
{	"card_id":	51	,	"category_id":	7	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	car rentals	"	},
{	"card_id":	51	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	52	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Emirates flights	"	},
{	"card_id":	52	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Eligible travel purchases	"	},
{	"card_id":	52	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	53	,	"category_id":	5	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Frontier purchases	"	},
{	"card_id":	53	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Restaurant purchases	"	},
{	"card_id":	53	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	54	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hawaiian Airlines purchases	"	},
{	"card_id":	54	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	54	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	gas	"	},
{	"card_id":	54	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	54	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	55	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	JetBlue purchases	"	},
{	"card_id":	55	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	55	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	grocery stores	"	},
{	"card_id":	55	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	56	,	"category_id":	5	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	JetBlue purchases	"	},
{	"card_id":	56	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	56	,	"category_id":	23	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	office supply stores	"	},
{	"card_id":	56	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	57	,	"category_id":	5	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	JetBlue purchases	"	},
{	"card_id":	57	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	57	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	grocery stores	"	},
{	"card_id":	57	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	58	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Lufthansa purchases	"	},
{	"card_id":	58	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	59	,	"category_id":	37	,	"bonus_point":	1.25	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All purchases	"	},
{	"card_id":	60	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Wyndham purchases	"	},
{	"card_id":	60	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Gas	"	},
{	"card_id":	60	,	"category_id":	19	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	utilities	"	},
{	"card_id":	60	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	60	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	61	,	"category_id":	6	,	"bonus_point":	8	,	"multiplier_type":	"	Points	"	,	"notes":	"	Wyndham purchases	"	},
{	"card_id":	61	,	"category_id":	26	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marketing	"	},
{	"card_id":	61	,	"category_id":	26	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	advertising	"	},
{	"card_id":	61	,	"category_id":	19	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	utilities	"	},
{	"card_id":	61	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	62	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Wyndham purchases	"	},
{	"card_id":	62	,	"category_id":	12	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Gas	"	},
{	"card_id":	62	,	"category_id":	19	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	utilities	"	},
{	"card_id":	62	,	"category_id":	8	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	62	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	63	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hawaiian Airlines purchases	"	},
{	"card_id":	63	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	63	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	gas	"	},
{	"card_id":	63	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	63	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	64	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Breeze Airways purchases	"	},
{	"card_id":	64	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	64	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	64	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	65	,	"category_id":	30	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Xbox products	"	},
{	"card_id":	65	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Streaming	"	},
{	"card_id":	65	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining purchases	"	},
{	"card_id":	65	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	66	,	"category_id":	14	,	"bonus_point":	8	,	"multiplier_type":	"	Points	"	,	"notes":	"	Rideshare	"	},
{	"card_id":	66	,	"category_id":	15	,	"bonus_point":	8	,	"multiplier_type":	"	Points	"	,	"notes":	"	taxi purchases	"	},
{	"card_id":	66	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel booked through Brex Travel	"	},
{	"card_id":	66	,	"category_id":	2	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Eligible restaurants	"	},
{	"card_id":	66	,	"category_id":	1	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	66	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Recurring software subscriptions	"	},
{	"card_id":	66	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	67	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	67	,	"category_id":	1	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	U.S. dining	"	},
{	"card_id":	67	,	"category_id":	8	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	groceries	"	},
{	"card_id":	67	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	68	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Aer Lingus	"	},
{	"card_id":	68	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	British Airways	"	},
{	"card_id":	68	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Iberia	"	},
{	"card_id":	68	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Hotel accommodations	"	},
{	"card_id":	68	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Avios	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	69	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Air Canada purchases	"	},
{	"card_id":	69	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	69	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	travel purchases	"	},
{	"card_id":	69	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	70	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	British Airways	"	},
{	"card_id":	70	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Iberia	"	},
{	"card_id":	70	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Aer Lingus	"	},
{	"card_id":	70	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Hotel accommodations	"	},
{	"card_id":	70	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Avios	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	71	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Disney locations	"	},
{	"card_id":	71	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Gas	"	},
{	"card_id":	71	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	grocery	"	},
{	"card_id":	71	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	dining	"	},
{	"card_id":	71	,	"category_id":	18	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Disney	"	},
{	"card_id":	71	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	72	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All purchases	"	},
{	"card_id":	73	,	"category_id":	33	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Rotating categories	"	},
{	"card_id":	73	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Travel booked through Chase Ultimate	"	},
{	"card_id":	73	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Dining	"	},
{	"card_id":	73	,	"category_id":	28	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	drugstores	"	},
{	"card_id":	73	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	74	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Travel booked through Chase Ultimate	"	},
{	"card_id":	74	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Dining	"	},
{	"card_id":	74	,	"category_id":	28	,	"bonus_point":	3	,	"multiplier_type":	"	Percent	"	,	"notes":	"	drugstores	"	},
{	"card_id":	74	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	75	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Iberia	"	},
{	"card_id":	75	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	British Airways	"	},
{	"card_id":	75	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Aer Lingus	"	},
{	"card_id":	75	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Avios	"	,	"notes":	"	Hotel accommodations	"	},
{	"card_id":	75	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Avios	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	76	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	IHG purchases	"	},
{	"card_id":	76	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	76	,	"category_id":	1	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	76	,	"category_id":	12	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas station	"	},
{	"card_id":	76	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	77	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	IHG purchases	"	},
{	"card_id":	77	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	77	,	"category_id":	1	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	77	,	"category_id":	12	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas station	"	},
{	"card_id":	77	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	78	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	IHG purchases	"	},
{	"card_id":	78	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	78	,	"category_id":	19	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	utilities	"	},
{	"card_id":	78	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	streaming	"	},
{	"card_id":	78	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	79	,	"category_id":	23	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Office supply	"	},
{	"card_id":	79	,	"category_id":	21	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	internet	"	},
{	"card_id":	79	,	"category_id":	20	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	cable	"	},
{	"card_id":	79	,	"category_id":	21	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	phone	"	},
{	"card_id":	79	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Gas stations	"	},
{	"card_id":	79	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	restaurants	"	},
{	"card_id":	79	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	80	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	80	,	"category_id":	24	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	shipping	"	},
{	"card_id":	80	,	"category_id":	24	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	internet	"	},
{	"card_id":	80	,	"category_id":	20	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	cable	"	},
{	"card_id":	80	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	81	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All purchases	"	},
{	"card_id":	82	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Every purchase	"	},
{	"card_id":	82	,	"category_id":	34	,	"bonus_point":	2.5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Purchases over $5,000	"	},
{	"card_id":	83	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	83	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel purchases	"	},
{	"card_id":	83	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	84	,	"category_id":	6	,	"bonus_point":	6	,	"multiplier_type":	"	Points	"	,	"notes":	"	Marriott purchases	"	},
{	"card_id":	84	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other travel purchases	"	},
{	"card_id":	84	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	85	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel via Chase Ultimate Rewards	"	},
{	"card_id":	85	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	85	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	streaming	"	},
{	"card_id":	85	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	online groceries	"	},
{	"card_id":	85	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other travel purchases	"	},
{	"card_id":	85	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	86	,	"category_id":	1	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Chase Dining	"	},
{	"card_id":	86	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	hotels	"	},
{	"card_id":	86	,	"category_id":	7	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals	"	},
{	"card_id":	86	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Air travel via Ultimate Rewards	"	},
{	"card_id":	86	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	86	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	other travel	"	},
{	"card_id":	86	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	87	,	"category_id":	5	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Southwest purchases	"	},
{	"card_id":	87	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Rapid Rewards hotel & car rentals	"	},
{	"card_id":	87	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Local transit	"	},
{	"card_id":	87	,	"category_id":	14	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	rideshare	"	},
{	"card_id":	88	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Southwest purchases	"	},
{	"card_id":	88	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Local transit	"	},
{	"card_id":	88	,	"category_id":	14	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	rideshare	"	},
{	"card_id":	89	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Southwest purchases	"	},
{	"card_id":	89	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Local transit	"	},
{	"card_id":	89	,	"category_id":	14	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	rideshare	"	},
{	"card_id":	90	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Southwest purchases	"	},
{	"card_id":	90	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Rapid Rewards hotel & car rentals	"	},
{	"card_id":	91	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Southwest purchases	"	},
{	"card_id":	91	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Local transit	"	},
{	"card_id":	91	,	"category_id":	14	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	rideshare	"	},
{	"card_id":	92	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	92	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	dining	"	},
{	"card_id":	92	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	gas stations	"	},
{	"card_id":	93	,	"category_id":	5	,	"bonus_point":	4	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	93	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	93	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	travel purchases	"	},
{	"card_id":	93	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	94	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	94	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	94	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	travel purchases	"	},
{	"card_id":	94	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	95	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	95	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	dining	"	},
{	"card_id":	95	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	hotel stays	"	},
{	"card_id":	95	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	96	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	96	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Local transit	"	},
{	"card_id":	96	,	"category_id":	14	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	rideshare	"	},
{	"card_id":	96	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	97	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	United purchases	"	},
{	"card_id":	97	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	97	,	"category_id":	18	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	streaming	"	},
{	"card_id":	97	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	other travel	"	},
{	"card_id":	98	,	"category_id":	6	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hyatt purchases	"	},
{	"card_id":	98	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	98	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	flights	"	},
{	"card_id":	98	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	local transit	"	},
{	"card_id":	98	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	99	,	"category_id":	6	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hyatt purchases	"	},
{	"card_id":	99	,	"category_id":	32	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Top three spending categories (quarterly)	"	},
{	"card_id":	99	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	100	,	"category_id":	16	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Amazon.com	"	},
{	"card_id":	100	,	"category_id":	8	,	"bonus_point":	5	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Whole Foods	"	},
{	"card_id":	100	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	100	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	gas	"	},
{	"card_id":	100	,	"category_id":	28	,	"bonus_point":	2	,	"multiplier_type":	"	Percent	"	,	"notes":	"	drugstores	"	},
{	"card_id":	100	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Percent	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	101	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	102	,	"category_id":	1	,	"bonus_point":	4	,	"multiplier_type":	"	%	"	,	"notes":	"	Dining	"	},
{	"card_id":	102	,	"category_id":	35	,	"bonus_point":	4	,	"multiplier_type":	"	%	"	,	"notes":	"	entertainment	"	},
{	"card_id":	102	,	"category_id":	18	,	"bonus_point":	4	,	"multiplier_type":	"	%	"	,	"notes":	"	streaming	"	},
{	"card_id":	102	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	%	"	,	"notes":	"	Grocery store purchases	"	},
{	"card_id":	102	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	%	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	103	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	104	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	105	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	106	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	107	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	107	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hotels	"	},
{	"card_id":	107	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	rental cars (Capital One Travel)	"	},
{	"card_id":	108	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	108	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hotels	"	},
{	"card_id":	108	,	"category_id":	4	,	"bonus_point":	10	,	"multiplier_type":	"	Miles	"	,	"notes":	"	rental cars (Capital One Travel)	"	},
{	"card_id":	108	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Flights (Capital One Travel)	"	},
{	"card_id":	109	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	109	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hotels	"	},
{	"card_id":	109	,	"category_id":	4	,	"bonus_point":	10	,	"multiplier_type":	"	Miles	"	,	"notes":	"	rental cars (Capital One Travel)	"	},
{	"card_id":	109	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Flights (Capital One Travel)	"	},
{	"card_id":	109	,	"category_id":	37	,	"bonus_point":	1.25	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	110	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Hotels	"	},
{	"card_id":	110	,	"category_id":	4	,	"bonus_point":	5	,	"multiplier_type":	"	Miles	"	,	"notes":	"	rental cars (Capital One Travel)	"	},
{	"card_id":	111	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines purchases	"	},
{	"card_id":	111	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	112	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines purchases	"	},
{	"card_id":	112	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Grocery stores (including grocery delivery)	"	},
{	"card_id":	112	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	113	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines	"	},
{	"card_id":	113	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	dining	"	},
{	"card_id":	113	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	gas station purchases	"	},
{	"card_id":	113	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	114	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	American Airlines	"	},
{	"card_id":	114	,	"category_id":	20	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	telecom	"	},
{	"card_id":	114	,	"category_id":	20	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	cable	"	},
{	"card_id":	114	,	"category_id":	7	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	car rentals	"	},
{	"card_id":	114	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	gas station purchases	"	},
{	"card_id":	114	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	115	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	116	,	"category_id":	32	,	"bonus_point":	5	,	"multiplier_type":	"	%	"	,	"notes":	"	Top eligible spending category (up to $500 per cycle)	"	},
{	"card_id":	116	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	%	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	117	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Hotels	"	},
{	"card_id":	117	,	"category_id":	7	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Car Rentals	"	},
{	"card_id":	117	,	"category_id":	4	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Attractions (via Citi Travel)	"	},
{	"card_id":	117	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Air Travel	"	},
{	"card_id":	117	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Other Hotel Purchases	"	},
{	"card_id":	117	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	117	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Supermarkets	"	},
{	"card_id":	117	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Gas Stations	"	},
{	"card_id":	117	,	"category_id":	13	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	EV Charging Stations	"	},
{	"card_id":	117	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All Other Purchases	"	},
{	"card_id":	118	,	"category_id":	9	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Supermarkets	"	},
{	"card_id":	118	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas station purchases (up to $6,000/year)	"	},
{	"card_id":	118	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	119	,	"category_id":	19	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	AT&T products	"	},
{	"card_id":	119	,	"category_id":	19	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	services	"	},
{	"card_id":	119	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	120	,	"category_id":	33	,	"bonus_point":	5	,	"multiplier_type":	"	%	"	,	"notes":	"	Rotating categories (up to $1,500/quarter)	"	},
{	"card_id":	120	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	%	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	121	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	LATAM Airlines purchases	"	},
{	"card_id":	121	,	"category_id":	2	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	121	,	"category_id":	31	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	international purchases	"	},
{	"card_id":	121	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	122	,	"category_id":	5	,	"bonus_point":	4	,	"multiplier_type":	"	Miles	"	,	"notes":	"	LATAM Airlines purchases	"	},
{	"card_id":	122	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	U.S. restaurants	"	},
{	"card_id":	122	,	"category_id":	31	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	international purchases	"	},
{	"card_id":	122	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	123	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Qatar Airways purchases	"	},
{	"card_id":	123	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	123	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	123	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	groceries	"	},
{	"card_id":	123	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	124	,	"category_id":	5	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Qatar Airways purchases	"	},
{	"card_id":	124	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	124	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	124	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	groceries	"	},
{	"card_id":	124	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	125	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Avianca purchases	"	},
{	"card_id":	125	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Gas	"	},
{	"card_id":	125	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	125	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	126	,	"category_id":	5	,	"bonus_point":	4	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Avianca purchases	"	},
{	"card_id":	126	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Gas	"	},
{	"card_id":	126	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	grocery purchases	"	},
{	"card_id":	126	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	127	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Amtrak travel	"	},
{	"card_id":	127	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	127	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	travel	"	},
{	"card_id":	127	,	"category_id":	11	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	transit	"	},
{	"card_id":	127	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	128	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Amtrak travel	"	},
{	"card_id":	128	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	129	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Best Western purchases	"	},
{	"card_id":	129	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	130	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Best Western purchases	"	},
{	"card_id":	130	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	131	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	% Cash Back	"	,	"notes":	"	All purchases	"	},
{	"card_id":	132	,	"category_id":	12	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Gas purchases at the pump	"	},
{	"card_id":	132	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Supermarket purchases	"	},
{	"card_id":	132	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	133	,	"category_id":	4	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel purchases (Honors Members)	"	},
{	"card_id":	133	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel purchases (Others)	"	},
{	"card_id":	133	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	134	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	135	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Asia Miles	"	,	"notes":	"	Cathay Pacific purchases	"	},
{	"card_id":	135	,	"category_id":	1	,	"bonus_point":	1.5	,	"multiplier_type":	"	Asia Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	135	,	"category_id":	31	,	"bonus_point":	1.5	,	"multiplier_type":	"	Asia Miles	"	,	"notes":	"	foreign currency purchases	"	},
{	"card_id":	135	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Asia Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	136	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Prepaid hotels	"	},
{	"card_id":	136	,	"category_id":	7	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals booked in Altitude Rewards Center	"	},
{	"card_id":	136	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Eligible travel purchases	"	},
{	"card_id":	136	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	137	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Prepaid hotels	"	},
{	"card_id":	137	,	"category_id":	7	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals booked in Altitude Rewards Center	"	},
{	"card_id":	137	,	"category_id":	4	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Eligible travel purchases	"	},
{	"card_id":	137	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Gas station purchases	"	},
{	"card_id":	137	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	138	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Prepaid hotel stays	"	},
{	"card_id":	138	,	"category_id":	7	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals booked through the Altitude Rewards Center	"	},
{	"card_id":	138	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	flights	"	},
{	"card_id":	138	,	"category_id":	6	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	hotels	"	},
{	"card_id":	138	,	"category_id":	7	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals	"	},
{	"card_id":	138	,	"category_id":	15	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	taxis	"	},
{	"card_id":	138	,	"category_id":	37	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Mobile wallet purchases	"	},
{	"card_id":	139	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	139	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Prepaid hotels	"	},
{	"card_id":	139	,	"category_id":	7	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals booked in Altitude Rewards Center	"	},
{	"card_id":	139	,	"category_id":	4	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Travel	"	},
{	"card_id":	139	,	"category_id":	12	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas station purchases	"	},
{	"card_id":	139	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	139	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining purchases	"	},
{	"card_id":	139	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	139	,	"category_id":	1	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining	"	},
{	"card_id":	139	,	"category_id":	1	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	takeout	"	},
{	"card_id":	139	,	"category_id":	11	,	"bonus_point":	4	,	"multiplier_type":	"	Points	"	,	"notes":	"	delivery purchases	"	},
{	"card_id":	139	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	139	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	139	,	"category_id":	18	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	streaming services	"	},
{	"card_id":	139	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	140	,	"category_id":	32	,	"bonus_point":	5	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Two chosen categories (up to $2,000 per quarter)	"	},
{	"card_id":	140	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	grocery stores	"	},
{	"card_id":	140	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	gas stations)	"	},
{	"card_id":	140	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	141	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Dining purchases	"	},
{	"card_id":	141	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Airline	"	},
{	"card_id":	141	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas station purchases	"	},
{	"card_id":	141	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	142	,	"category_id":	32	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Top two spending categories each month	"	},
{	"card_id":	142	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	143	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Gas stations	"	},
{	"card_id":	143	,	"category_id":	23	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	office supply stores	"	},
{	"card_id":	143	,	"category_id":	22	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	cell phone services	"	},
{	"card_id":	143	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	restaurants	"	},
{	"card_id":	143	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	144	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All purchases	"	},
{	"card_id":	145	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Korean Air purchases	"	},
{	"card_id":	145	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	146	,	"category_id":	5	,	"bonus_point":	3	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Korean Air purchases	"	},
{	"card_id":	146	,	"category_id":	1	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Dining	"	},
{	"card_id":	146	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	hotel purchases	"	},
{	"card_id":	146	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	147	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Miles	"	,	"notes":	"	Korean Air purchases	"	},
{	"card_id":	147	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Miles	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	148	,	"category_id":	32	,	"bonus_point":	6	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Two chosen retailers (first $1,500 per quarter)	"	},
{	"card_id":	148	,	"category_id":	8	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	148	,	"category_id":	25	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	wholesale clubs	"	},
{	"card_id":	148	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	gas stations	"	},
{	"card_id":	148	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	Cash Back	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	149	,	"category_id":	37	,	"bonus_point":	1.5	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	150	,	"category_id":	37	,	"bonus_point":	2	,	"multiplier_type":	"	%	"	,	"notes":	"	All purchases	"	},
{	"card_id":	151	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	151	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	travel	"	},
{	"card_id":	151	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	151	,	"category_id":	11	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	transit	"	},
{	"card_id":	151	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	streaming services	"	},
{	"card_id":	151	,	"category_id":	22	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	phone plans	"	},
{	"card_id":	151	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	152	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	Restaurants	"	},
{	"card_id":	152	,	"category_id":	4	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	travel	"	},
{	"card_id":	152	,	"category_id":	12	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas stations	"	},
{	"card_id":	152	,	"category_id":	11	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	transit	"	},
{	"card_id":	152	,	"category_id":	18	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	streaming services	"	},
{	"card_id":	152	,	"category_id":	22	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	phone plans	"	},
{	"card_id":	152	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	153	,	"category_id":	6	,	"bonus_point":	5	,	"multiplier_type":	"	Points	"	,	"notes":	"	Choice Hotels purchases	"	},
{	"card_id":	153	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	153	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas purchases	"	},
{	"card_id":	153	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	154	,	"category_id":	6	,	"bonus_point":	10	,	"multiplier_type":	"	Points	"	,	"notes":	"	Choice Hotels purchases	"	},
{	"card_id":	154	,	"category_id":	8	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	Grocery stores	"	},
{	"card_id":	154	,	"category_id":	12	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	gas purchases	"	},
{	"card_id":	154	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
{	"card_id":	156	,	"category_id":	36	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	Rent payments made through the Bilt App or website	"	},
{	"card_id":	156	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	dining	"	},
{	"card_id":	156	,	"category_id":	2	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	restaurants	"	},
{	"card_id":	156	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	takeout	"	},
{	"card_id":	156	,	"category_id":	1	,	"bonus_point":	3	,	"multiplier_type":	"	Points	"	,	"notes":	"	delivery	"	},
{	"card_id":	156	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	travel	"	},
{	"card_id":	156	,	"category_id":	5	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	flights	"	},
{	"card_id":	156	,	"category_id":	6	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	hotels	"	},
{	"card_id":	156	,	"category_id":	7	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	car rentals	"	},
{	"card_id":	156	,	"category_id":	4	,	"bonus_point":	2	,	"multiplier_type":	"	Points	"	,	"notes":	"	cruises	"	},
{	"card_id":	156	,	"category_id":	37	,	"bonus_point":	1	,	"multiplier_type":	"	Points	"	,	"notes":	"	All other purchases	"	},
        ]

        # Fetch valid card and category IDs
        valid_card_ids = {card.id for card in Card.query.all()}
        valid_category_ids = {category.id for category in Category.query.all()}

        # Log fetched valid IDs for debugging
        print(f"Valid card IDs: {valid_card_ids}")
        print(f"Valid category IDs: {valid_category_ids}")

        # Validate reward point references and data integrity
        invalid_entries = [
            rp for rp in reward_points_data
            if rp["card_id"] not in valid_card_ids
            or rp["category_id"] not in valid_category_ids
            or not isinstance(rp["bonus_point"], (int, float))
            or rp["bonus_point"] <= 0
        ]

        if invalid_entries:
            print("Invalid reward point references detected:")
            for invalid in invalid_entries:
                print(f"  {invalid}")
            print("Skipping invalid entries.")
            return

        # Remove duplicates by checking existing entries
        existing_points = RewardPoint.query.with_entities(
            RewardPoint.card_id, RewardPoint.category_id
        ).all()
        existing_set = {(ep[0], ep[1]) for ep in existing_points}

        new_entries = [
            rp for rp in reward_points_data
            if (rp["card_id"], rp["category_id"]) not in existing_set
        ]

        if not new_entries:
            print("No new reward points to insert.")
            return

        # Log new entries for debugging
        print(f"New reward points to insert: {new_entries}")

        # Prepare RewardPoint objects for bulk insert
        reward_points_objects = [
            RewardPoint(
                card_id=rp["card_id"],
                category_id=rp["category_id"],
                bonus_point=rp["bonus_point"],
                multiplier_type=rp["multiplier_type"].strip().capitalize(),
                notes=rp["notes"]  # Set the notes field
            ) for rp in new_entries
        ]

        # Bulk insert reward points
        db.session.bulk_save_objects(reward_points_objects)
        db.session.commit()
        print("Reward points seeding completed successfully.")

    except Exception as e:
        print(f"An error occurred during seeding: {e}")
        db.session.rollback()


def undo_reward_points():
    """
    Removes all reward points from the database and resets primary keys.
    """
    try:
        # Check if the `reward_points` table exists using the inspector
        inspector = inspect(db.engine)
        table_exists = inspector.has_table("reward_points", schema=SCHEMA if environment == "production" else None)

        if not table_exists:
            print(f"The reward_points table does not exist in the schema {SCHEMA}. Skipping undo.")
            return

        # Remove all entries from the reward_points table
        if environment == "production":
            db.session.execute(f"TRUNCATE TABLE {SCHEMA}.reward_points RESTART IDENTITY CASCADE;")
        else:
            db.session.execute(text("DELETE FROM reward_points"))
        db.session.commit()
        print("Reward points table cleared successfully.")
    except Exception as e:
        print(f"An error occurred while clearing the reward points table: {e}")
        db.session.rollback()
