"""empty message

Revision ID: 5202aeb4c9ed
Revises: 51881d7c48cb
Create Date: 2024-12-05 17:47:09.499188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5202aeb4c9ed'
down_revision = '51881d7c48cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spendings', schema=None) as batch_op:
        batch_op.drop_constraint('spendings_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('wallet_cards', schema=None) as batch_op:
        batch_op.drop_constraint('wallet_cards_wallet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('wallet_cards_card_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_cards', schema=None) as batch_op:
        batch_op.create_foreign_key('wallet_cards_card_id_fkey', 'cards', ['card_id'], ['id'])
        batch_op.create_foreign_key('wallet_cards_wallet_id_fkey', 'wallets', ['wallet_id'], ['id'])

    with op.batch_alter_table('spendings', schema=None) as batch_op:
        batch_op.create_foreign_key('spendings_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
